#!/bin/csh -x
#==================================================================
# Setup Bluefire job parameters
#BSUB -P PROJ_NUMBER
#BSUB -x
#BSUB -n NUM_TASKS
#BSUB -R "span[ptile=TASKS_PER_NODE]"
#BSUB -J JOB_NAME
#BSUB -o JOB_NAME.out
#BSUB -e JOB_NAME.err
#BSUB -W JOB_TIME
#BSUB -q JOB_CLASS
#==================================================================
#
# Remove previous job output files
rm -Rf rsl.out*
rm -Rf rsl.err*
rm -Rf JOB_NAME.out
rm -Rf JOB_NAME.err
unalias cd
unalias ls
#
#
# Setup lsf profile
. /usr/local/lsf/conf/profile.lsf
#
set myname = $0     # this is the name of this script
set start_time = `date +%s`
echo "host is " `hostname`
cd RUN_DIR
if (! -d RUN_DIR/logs) mkdir RUN_DIR/logs
#
#  copy files to appropriate location
echo $start_time >&! logs/start_memberENS_MEM
set icnum = `echo ENS_MEM + 10000 | bc | cut -b2-5`
#
if(-e filter_control${icnum}) rm -rf filter_control${icnum}
echo ENS_MEM                       >! filter_control${icnum}
echo assim_model_state_ic.${icnum} >> filter_control${icnum}
echo assim_model_state_ud.${icnum} >> filter_control${icnum}
#
#  integrate the model forward in time
cd RUN_DIR
./advance_model.csh ENS_MEM 1 filter_control${icnum} WRFINPUT_DIR ICYCLE
#
set end_time = `date  +%s`
@ length_time = $end_time - $start_time
echo "duration_sec = $length_time"
