#!/bin/ksh
############################################
#
# Modifed by APM to submit job to Bluefire
#
############################################
#
# Move to run directory
cd RUN_DIR
#
# Setup Bluefire job parameters
#BSUB -P PROJ_NUMBER
#BSUB -x
#BSUB -n NUM_TASKS
#BSUB -R "span[ptile=TASKS_PER_NODE]"
#BSUB -J JOB_NAME
#BSUB -o JOB_NAME.out
#BSUB -e JOB_NAME.err
#BSUB -W JOB_TIME
#BSUB -q JOB_CLASS
#
# Remove previous job output files
rm -Rf rsl.out*
rm -Rf rsl.err*
rm -Rf JOB_NAME.out
rm -Rf JOB_NAME.err
#
# Setup lsf profile
. /usr/local/lsf/conf/profile.lsf
#
# Submit job
#rm -RF filter_started
#rm -RF filter_done
#export start_time = `date +%s`
#echo $start_time > filter_started
touch filter_started
#
mpirun.lsf /usr/local/bin/launch ./filter
#
#export end_time = `date +%s`
#echo $end_time > filter_ended
touch filter_done
