#!/bin/csh
#####################################################################
#==================================================================
#BSUB -J step_post
#BSUB -o step_post.%J.log
#BSUB -P GAU_NUMBER
#BSUB -W 1:30
#BSUB -q share
#BSUB -n 1
#BSUB -R span[ptile=1]
#==================================================================

# NEED TO SWAP 
#set this_time = 20090601_06
set this_time = TIME_PATH

set save_path = mss:/ARELLANO/WRFDART/runA
set  save_cmd = 'msrcp -pe 2000 '
set  ens_size = 50
set      MOVE = '/bin/mv -f'

# NEED TO SWAP 
set OUTPUTDIR = FULL_OUT

# NEED TO SWAP ?
#set CENTRALDIR = `pwd`
set CENTRALDIR = RUN_DIR
# saves done as follows: $save_cmd $save_file $save_path/$this_time/$save_file

set member_num = 1
while($member_num <= $ens_size)
# save the restart_file
  set mem4=`printf %04d $member_num`
  set save_file = filter_ic.$mem4
  set   ic_file = filter_ic.$mem4
  set wrfin_file = $CENTRALDIR/advance_temp$member_num/wrfinput_d01
  echo Saving member $member_num as: $save_cmd $OUTPUTDIR/$save_file $save_path/$this_time/$save_file
  $save_cmd $OUTPUTDIR/$save_file $save_path/$this_time/$save_file
# rename the restart file to input file
#  echo Rename member $member_num : $MOVE $CENTRALDIR/$save_file $CENTRALDIR/$ic_file
#  $MOVE $CENTRALDIR/$save_file $CENTRALDIR/$ic_file
# save the wrfout files
  set save_file = wrfinput_d01.$mem4
  echo Saving wrfout $member_num as: $save_cmd $wrfin_file $save_path/$this_time/$save_file
  $save_cmd $wrfin_file $save_path/$this_time/$save_file
  @ member_num ++
end
# save the run text output
  set tarcmd = `tar -cvf log_files.tar *.log`
  $tarcmd
  set save_file = log_files.tar
  echo saving log files as $save_cmd $CENTRALDIR/$save_file $save_path/$this_time/$save_file
  $save_cmd $CENTRALDIR/$save_file $save_path/$this_time/$save_file
  rm log_files.tar *.log 
  set tarcmd = `tar -cvf wrfout_files.tar $CENTRALDIR/WRFOUT/wrf.out*`
  $tarcmd
  set save_file = wrfout_files.tar
  echo saving wrfout files as $save_cmd $CENTRALDIR/$save_file $save_path/$this_time/$save_file
  $save_cmd $CENTRALDIR/$save_file $save_path/$this_time/$save_file
  rm wrfout_files.tar $CENTRALDIR/WRFOUT/wrf.out*
# save the obs_seq.final
  set save_file = obs_seq.final
  echo obs_seq.final $save_cmd $OUTPUTDIR/$save_file $save_path/$this_time/$save_file
  $save_cmd $OUTPUTDIR/$save_file $save_path/$this_time/$save_file
# save the state space diagnostics
  set save_file = Prior_Diag.nc
  echo $save_cmd $OUTPUTDIR/$save_file $save_path/$this_time/$save_file
  $save_cmd $OUTPUTDIR/$save_file $save_path/$this_time/$save_file
  set save_file = Posterior_Diag.nc
  echo $save_cmd $OUTPUTDIR/$save_file $save_path/$this_time/$save_file
  $save_cmd $OUTPUTDIR/$save_file $save_path/$this_time/$save_file
# save the inflation
  set save_file = prior_inf_ic
  echo $save_cmd $OUTPUTDIR/$save_file $save_path/$this_time/$save_file
  $save_cmd $OUTPUTDIR/$save_file $save_path/$this_time/$save_file
  touch save_done
exit 0
